meta:
  model_name: deit_small
  master_port: 8888
  load_checkpoint: false
  training: true
  copy_data: false
  device: cuda:0
data:
  root_path: .
  image_folder: /imagenet/
  num_classes: 1000
optimization:
  weight_decay: 0.0
  lr: 6.4
  epochs: 100
  num_blocks: 1
  normalize: true
logging:
  folder: ./checkpoint/msn_logs/
  write_tag: msn-lineval-experiment-linear-eval
  pretrain_path: /scratch/projects/shamoutlab/ds5749/msn/pretrained/vits16_800ep.pth.tar
