meta:
  model_name: LSTM
  master_port: 8888
  load_checkpoint: True
  training: true
  copy_data: false
  device: cuda:0
data:
  root_path: .
  image_folder: /imagenet/
  num_classes: 25
optimization:
  weight_decay: 0.0
  lr: 6.4
  epochs: 100
  num_blocks: 1
  normalize: true
logging:
  folder: ./checkpoint/msn_ehr_logs/
  write_tag: msn-lineval-experiment-ehr
  pretrain_path: /scratch/projects/shamoutlab/ds5749/multi-modal-msn/checkpoint/msn_ehr_logs/msn-ehr-experiment-vertical_and_horizontal-ep100.pth.tar
  # /scratch/projects/shamoutlab/ds5749/multi-modal-msn/checkpoint/msn_ehr_logs/msn-ehr-experiment-drop_start-ep100.pth.tar
  # /scratch/projects/shamoutlab/ds5749/multi-modal-msn/checkpoint/msn_ehr_logs/msn-ehr-experiment-vertical_horizontal-ep100.pth.tar
