meta:
  model_name: deit_small
  master_port: 8888
  load_checkpoint: True
  training: true
  copy_data: false
  # device: cpu
  device: cuda:0
data:
  root_path: .
  image_folder: /imagenet/
  num_classes: 25
optimization:
  weight_decay: 0.0
  lr: 6.4
  epochs: 100
  num_blocks: 1
  normalize: true
logging:
  folder: checkpoint/msn_logs/
  write_tag: msn-lineval-experiment-linear-eval-fusion-128
  pretrain_path: /scratch/projects/shamoutlab/ds5749/multi-modal-msn/checkpoint/msn_fusion_logs/msn-experiment-fusion-128-latest.pth.tar
  # /scratch/projects/shamoutlab/ds5749/multi-modal-msn/checkpoint/msn_fusion_logs/msn-experiment-fusion-256-latest.pth.tar
